W4D4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resource :session, only: [:new, :create, :destroy]
end

W4D4/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W4D4/MusicApp/app/models/user.rb
class User < ApplicationRecord
    before_validation :ensure_session_token
    validates :email, :password_digest, :session_token, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }
    attr_reader :password


    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user 
        else 
            return nil 
        end 
    end 

    def self.generate_session_token
        self.session_token = SecureRandom.urlsafe_base64 
    end
    
    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64 
        self.save!
        self.session_token
    end 

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end

    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end 


end 

W4D4/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def require_login 
        redirect_to new_session_url unless logged_in?
    end 

    def require_logout 
        redirect_to users_url if logged_in?
    end 

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])

    end 

    def logged_in?
        !!current_user
    end 

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end 

    def logout!
        if current_user 
            current_user.reset_session_token!
        end 
        session[:session_token] = nil
    end 
end

W4D4/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logout, only: [:new, :create]

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W4D4/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end 

    def edit 
        @user = User.find(params[:id])
    end 

    def index 
        @user = User.all
    end 

    def show 
        @user = User.find(params[:id])
    end 

    def create 
        @user = User.new(user_params)

        if @user.save 
            login!(@user)
            redirect_to user_url(@user)
        else 
            flash.now[:errors] = @user.errors.full_messages 
            render :new
        end 
    end 

    def update 
        @user = User.find(params[:id])

        if @user.update(user_params)
            redirect_to user_url(@user)
        end 
    end 

    def destroy
        @user = User.find(params[:id])
        @user.destroy 
        redirect_to users_url
    end 

    private 

    def user_params 
        params.require(:user).permit(:email, :password, :password_digest, :session_token)
    end 

end

W4D4/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

W4D4/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D4/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

W4D4/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>MusiCity</h1>
    <% if logged_in? %>
      <h2>Welcome, <%=current_user.email%></h2>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
    <% else %>
    <div class= "button_log">
      <a class = "button" href="<%=new_user_url%>">Sign Up</a>
      <a class = "button" href="<%=new_session_url%>">Sign In</a>
    </div>
    <% end %>
    <% if flash.now[:errors] %>
      <% flash.now[:errors].each do |error| %>
        <%= error %>
     <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

W4D4/MusicApp/app/views/users/_form.html.erb
<% if type == :new %>
  <% action_url = users_url %>
  <% button_text = "Sign Up" %>
<% elsif type == :edit %>
  <% action_url = user_url(user) %>
  <% button_text = "Edit Artist" %>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="email">Email:
    <input type="text" name="user[email]" value="<%= user.email %>">
  </label>
  <br>
  <label for="password">Password:
    <input type="password" name="user[password]" value="<%= %>">
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

W4D4/MusicApp/app/views/users/_user.html.erb
<ul>
  <% if action == :show %>
    <li>Email:
      <%= user.email %>
    </li>
  <% end %>
  <% if action == :index %>
    <a href="<%= user_url(user) %>">Show me this artist</a>
  <% elsif action == :show %>
    <a href="<%= users_url %>">All Artists</a>
  <% end %>
  <br>
  <a href="<%= edit_user_url(user) %>">Edit Artist Profile</a>
  <br>
  <form action="<%= user_url(user) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Delete Artist">
  </form>
</ul>

W4D4/MusicApp/app/views/users/edit.html.erb
<h1> Edit Artist Profile </h1>
<%= render 'form', user: @user, action: :edit %>

W4D4/MusicApp/app/views/users/index.html.erb
<!-- <h1> Music City </h1> -->
<a href="<%= new_user_url %>"> New Artist </a>

<ul>    
    <% @user.each do |user| %>
      <li>    
        <%= render 'user', user: user, action: :index %>
      </li>
      <br> 
    <% end %>
</ul>

W4D4/MusicApp/app/views/users/new.html.erb
<h1> Create New Artist </h1>
<%= render 'form', user: @user, type: :new %>

W4D4/MusicApp/app/views/users/show.html.erb
<%= render 'user', user: @user, action: :show %>